name: Backend Test

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo backend test
      - name: Change folder and check
        run: ls && cd backend/ && pwd